# Generated by Django 5.2.7 on 2025-10-22 22:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Trabajadores',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('telefono', models.CharField(max_length=30)),
                ('cedula', models.CharField(max_length=20)),
                ('sueldo', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='TablaDatos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=20)),
                ('jerarquia', models.IntegerField()),
                ('padre', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='farmApp.tabladatos')),
            ],
        ),
        migrations.CreateModel(
            name='Huertos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hectareas', models.FloatField()),
                ('fecha_p', models.DateField()),
                ('categoria_h', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categoria_huertos', to='farmApp.tabladatos')),
            ],
        ),
        migrations.CreateModel(
            name='Animales',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('f_nacimiento', models.DateField()),
                ('n_partos', models.IntegerField()),
                ('categoria_a', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categoria_animales', to='farmApp.tabladatos')),
                ('genero', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='genero_animales', to='farmApp.tabladatos')),
                ('raza', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='raza_animales', to='farmApp.tabladatos')),
            ],
        ),
        migrations.CreateModel(
            name='Producciones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_produccion', models.DateField()),
                ('nombre', models.CharField(max_length=10)),
                ('peso_cantidad', models.FloatField()),
                ('categoria_p', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categoria_producciones', to='farmApp.tabladatos')),
                ('id_trabajadores', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='farmApp.trabajadores')),
            ],
        ),
        migrations.CreateModel(
            name='ActividadesHuertos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=100)),
                ('fecha', models.DateField()),
                ('retorno', models.IntegerField()),
                ('id_huerto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='farmApp.huertos')),
                ('id_trabajadores', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='farmApp.trabajadores')),
            ],
        ),
        migrations.CreateModel(
            name='ActividadesAnimales',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=100)),
                ('fecha', models.DateField()),
                ('retorno', models.IntegerField()),
                ('id_animales', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='farmApp.animales')),
                ('id_trabajadores', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='farmApp.trabajadores')),
            ],
        ),
    ]
