# Generated by Django 5.2.7 on 2025-11-19 03:08

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import farmApp.validators
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmApp', '0002_trabajadores_usuario_alter_animales_n_partos'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='actividadesanimales',
            options={'ordering': ['-fecha'], 'verbose_name': 'Actividad Animal', 'verbose_name_plural': 'Actividades Animales'},
        ),
        migrations.AlterModelOptions(
            name='actividadeshuertos',
            options={'ordering': ['-fecha'], 'verbose_name': 'Actividad Huerto', 'verbose_name_plural': 'Actividades Huertos'},
        ),
        migrations.AlterModelOptions(
            name='animales',
            options={'ordering': ['-f_nacimiento'], 'verbose_name': 'Animal', 'verbose_name_plural': 'Animales'},
        ),
        migrations.AlterModelOptions(
            name='huertos',
            options={'ordering': ['-fecha_p'], 'verbose_name': 'Huerto', 'verbose_name_plural': 'Huertos'},
        ),
        migrations.AlterModelOptions(
            name='producciones',
            options={'ordering': ['-fecha_produccion'], 'verbose_name': 'Producción', 'verbose_name_plural': 'Producciones'},
        ),
        migrations.AlterModelOptions(
            name='tabladatos',
            options={'ordering': ['jerarquia', 'nombre'], 'verbose_name': 'Dato de Referencia', 'verbose_name_plural': 'Datos de Referencia'},
        ),
        migrations.AlterModelOptions(
            name='trabajadores',
            options={'ordering': ['nombre'], 'verbose_name': 'Trabajador', 'verbose_name_plural': 'Trabajadores'},
        ),
        migrations.AddField(
            model_name='animales',
            name='activo',
            field=models.BooleanField(default=True, help_text='Marcar como inactivo si el animal ya no está en la finca', verbose_name='Activo'),
        ),
        migrations.AddField(
            model_name='animales',
            name='notas',
            field=models.TextField(blank=True, null=True, verbose_name='Notas adicionales'),
        ),
        migrations.AddField(
            model_name='huertos',
            name='activo',
            field=models.BooleanField(default=True, verbose_name='Activo'),
        ),
        migrations.AddField(
            model_name='huertos',
            name='notas',
            field=models.TextField(blank=True, null=True, verbose_name='Notas adicionales'),
        ),
        migrations.AddField(
            model_name='huertos',
            name='ubicacion',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Ubicación'),
        ),
        migrations.AddField(
            model_name='trabajadores',
            name='activo',
            field=models.BooleanField(default=True, verbose_name='Activo'),
        ),
        migrations.AddField(
            model_name='trabajadores',
            name='fecha_ingreso',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Fecha de ingreso'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='actividadesanimales',
            name='descripcion',
            field=models.CharField(max_length=100, verbose_name='Descripción'),
        ),
        migrations.AlterField(
            model_name='actividadesanimales',
            name='fecha',
            field=models.DateField(validators=[farmApp.validators.validate_fecha_no_futura], verbose_name='Fecha'),
        ),
        migrations.AlterField(
            model_name='actividadesanimales',
            name='id_animales',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='farmApp.animales', verbose_name='Animal'),
        ),
        migrations.AlterField(
            model_name='actividadesanimales',
            name='id_trabajadores',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='farmApp.trabajadores', verbose_name='Trabajador'),
        ),
        migrations.AlterField(
            model_name='actividadesanimales',
            name='retorno',
            field=models.IntegerField(help_text='Puede ser negativo en caso de gastos', validators=[farmApp.validators.validate_retorno_economico], verbose_name='Retorno económico'),
        ),
        migrations.AlterField(
            model_name='actividadeshuertos',
            name='descripcion',
            field=models.CharField(max_length=100, verbose_name='Descripción'),
        ),
        migrations.AlterField(
            model_name='actividadeshuertos',
            name='fecha',
            field=models.DateField(validators=[farmApp.validators.validate_fecha_no_futura], verbose_name='Fecha'),
        ),
        migrations.AlterField(
            model_name='actividadeshuertos',
            name='id_huerto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='farmApp.huertos', verbose_name='Huerto'),
        ),
        migrations.AlterField(
            model_name='actividadeshuertos',
            name='id_trabajadores',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='farmApp.trabajadores', verbose_name='Trabajador'),
        ),
        migrations.AlterField(
            model_name='actividadeshuertos',
            name='retorno',
            field=models.IntegerField(help_text='Puede ser negativo en caso de gastos', validators=[farmApp.validators.validate_retorno_economico], verbose_name='Retorno económico'),
        ),
        migrations.AlterField(
            model_name='animales',
            name='categoria_a',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categoria_animales', to='farmApp.tabladatos', verbose_name='Categoría'),
        ),
        migrations.AlterField(
            model_name='animales',
            name='f_nacimiento',
            field=models.DateField(validators=[farmApp.validators.validate_fecha_razonable_animal], verbose_name='Fecha de nacimiento'),
        ),
        migrations.AlterField(
            model_name='animales',
            name='genero',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='genero_animales', to='farmApp.tabladatos', verbose_name='Género'),
        ),
        migrations.AlterField(
            model_name='animales',
            name='n_partos',
            field=models.IntegerField(blank=True, help_text='Aplicable solo para hembras', null=True, validators=[farmApp.validators.validate_numero_partos], verbose_name='Número de partos'),
        ),
        migrations.AlterField(
            model_name='animales',
            name='raza',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='raza_animales', to='farmApp.tabladatos', verbose_name='Raza'),
        ),
        migrations.AlterField(
            model_name='huertos',
            name='categoria_h',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categoria_huertos', to='farmApp.tabladatos', verbose_name='Categoría'),
        ),
        migrations.AlterField(
            model_name='huertos',
            name='fecha_p',
            field=models.DateField(validators=[farmApp.validators.validate_fecha_no_futura], verbose_name='Fecha de plantación'),
        ),
        migrations.AlterField(
            model_name='huertos',
            name='hectareas',
            field=models.FloatField(validators=[farmApp.validators.validate_hectareas_positivas], verbose_name='Hectáreas'),
        ),
        migrations.AlterField(
            model_name='producciones',
            name='categoria_p',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categoria_producciones', to='farmApp.tabladatos', verbose_name='Categoría'),
        ),
        migrations.AlterField(
            model_name='producciones',
            name='fecha_produccion',
            field=models.DateField(validators=[farmApp.validators.validate_fecha_no_futura], verbose_name='Fecha de producción'),
        ),
        migrations.AlterField(
            model_name='producciones',
            name='id_trabajadores',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='farmApp.trabajadores', verbose_name='Trabajador responsable'),
        ),
        migrations.AlterField(
            model_name='producciones',
            name='nombre',
            field=models.CharField(max_length=10, verbose_name='Nombre del producto'),
        ),
        migrations.AlterField(
            model_name='producciones',
            name='peso_cantidad',
            field=models.FloatField(validators=[farmApp.validators.validate_peso_cantidad_positiva], verbose_name='Peso/Cantidad (kg)'),
        ),
        migrations.AlterField(
            model_name='tabladatos',
            name='jerarquia',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)]),
        ),
        migrations.AlterField(
            model_name='tabladatos',
            name='padre',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='hijos', to='farmApp.tabladatos'),
        ),
        migrations.AlterField(
            model_name='trabajadores',
            name='cedula',
            field=models.CharField(max_length=20, unique=True, validators=[farmApp.validators.validate_cedula_colombiana], verbose_name='Cédula'),
        ),
        migrations.AlterField(
            model_name='trabajadores',
            name='nombre',
            field=models.CharField(max_length=50, verbose_name='Nombre completo'),
        ),
        migrations.AlterField(
            model_name='trabajadores',
            name='sueldo',
            field=models.FloatField(validators=[farmApp.validators.validate_sueldo_positivo], verbose_name='Sueldo mensual'),
        ),
        migrations.AlterField(
            model_name='trabajadores',
            name='telefono',
            field=models.CharField(max_length=30, validators=[farmApp.validators.validate_telefono_colombia], verbose_name='Teléfono'),
        ),
        migrations.AlterField(
            model_name='trabajadores',
            name='usuario',
            field=models.OneToOneField(blank=True, help_text='Usuario del sistema vinculado', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='tabladatos',
            unique_together={('nombre', 'jerarquia')},
        ),
    ]
